/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Checkpoints {
  id: Generated<number>;
  lastProcessedSlot: string;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface OrderEvents {
  data: Json;
  id: Generated<number>;
  timestamp: Timestamp;
  type: string;
}

export interface Orders {
  createdAt: Timestamp;
  fulfilledAt: Timestamp | null;
  giveAmount: string;
  giveChainId: string;
  giveToken: string;
  orderId: string;
  takeAmount: string;
  takeChainId: string;
  takeToken: string;
  usdAmount: Numeric | null;
}

export interface DB {
  checkpoints: Checkpoints;
  orderEvents: OrderEvents;
  orders: Orders;
}
