/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IndexerMode = "historical" | "live";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DailyUsdVolume {
  createdVolumeUsd: Numeric;
  day: string;
  fulfilledVolumeUsd: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface Events {
  blockTime: Timestamp;
  eventType: string;
  id: Generated<number>;
  orderId: string;
  processed: Generated<boolean>;
  rawData: Json;
  signature: string;
  slot: string;
}

export interface IndexerState {
  lastSignature: string;
  mode: IndexerMode;
  programId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Orders {
  createdAt: Timestamp;
  fulfilledAt: Timestamp | null;
  giveAmount: string;
  giveChainId: string;
  giveToken: string;
  orderId: string;
  takeAmount: string;
  takeChainId: string;
  takeToken: string;
  usdAmount: Numeric | null;
}

export interface PriceCache {
  chainId: string;
  createdAt: Generated<Timestamp>;
  day: string;
  priceUsd: Numeric;
  source: string;
  token: string;
}

export interface Transactions {
  blockTime: Timestamp;
  processed: Generated<boolean>;
  programId: string;
  signature: string;
  slot: string;
}

export interface DB {
  dailyUsdVolume: DailyUsdVolume;
  events: Events;
  indexerState: IndexerState;
  orders: Orders;
  priceCache: PriceCache;
  transactions: Transactions;
}
